name: WINDOWS SERVER 2019

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-2019

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok . . .

      run: |
        Invoke-WebRequest https://github.com/David0l1/Free-RDP/blob/resource/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/David0l1/Free-RDP/resource/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/David0l1/Free-RDP/resource/loop.bat -OutFile loop.bat
        
    - name: Setting Up Ngrok . . .

      run: Expand-Archive ngrok.zip

    - name: Connecting To Ngrok . . .

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Setting Up Windows . . .

      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
    - name: Creating Tunnel . . .

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region=ap 3389"'

    - name: Connect To RDP

      run: cmd /c start.bat

    - name: Done.

      run: cmd /c loop.bat
